### ISSUE TITLE
User Story: About us page

### ISSUE THREAD

**Issue by joanavrsilva** [joanavrsilva/omega-gold#11]
As a **Site User** I can **see a little description about the company** so that **I can know more about the business history**

## Acceptance criteria:
1. The website must have a about us page;
2. The about us page explains the company history;
3. The About us page is simple, structure and easy to understand.

## Tasks:

- [ ] Add a About us page to nav bar;
- [ ] Create the text of the About us page;
- [ ] Add a image;
- [ ] Test the page responsiveness.
