### ISSUE TITLE
User Story: Products search

### ISSUE THREAD

**Issue by joanavrsilva** [joanavrsilva/omega-gold#19]
As a **Site User** I can **search the site for products** so that **I can be directed straight to it**

## Acceptance criteria:
1. The website must have a search bar;
2. The Site User can search for products;
3. The search bar is simple, structure and easy to use.

## Tasks:

- [ ] Add a search bar functionality;
- [ ] Add a search icon;
- [ ] Search products by name;
- [ ] Search products by category;
- [ ] Test the functionality.
