### ISSUE TITLE
User Story: Purchase confirmation

### ISSUE THREAD

**Issue by joanavrsilva** [joanavrsilva/omega-gold#5]
As a **Site User** I can **order and pay securely** so that **I receive a notification with my purchase confirmation**

## Acceptance criteria:
1. The website must have a order and payment system;
2. The order and payment system is simple and easy to understand;
3. The customers should receive by email a confirmation of their orders;
4. The email have all the information given in the order.

## Tasks:

- [ ] Create an template email;
- [ ] Add all the information by the costumer input in the email;
- [ ] Send to the client a email with the order and the purchase confirmation;
- [ ] Update register client orders;
- [ ] Test the functionality.
